# Generated by Django 4.1.3 on 2022-12-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_enquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name_plural': 'Banners'},
        ),
    ]
