# Generated by Django 4.1.3 on 2023-01-09 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_trainermsg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainermsg',
            name='user_type',
        ),
    ]
